### ISSUE TITLE
No way to set a password in PostgreSQLDatabaseConfig

### ISSUE THREAD

**Issue by twof** [vapor/fluent-postgresql#5] opened 2018-01-26 14:04 UTC
The initializer doesn't take a password.

**Comment by gperdomor** [comment] 2018-01-26 14:05
@twof the problem is here https://github.com/vapor/postgresql/pull/1#pullrequestreview-91845509 please close this because is related to `postgresql` lib :D

**Closed** 2018-01-26 14:06 UTC
